### ISSUE TITLE
Date picker in input: calendar doesn't close when input is inside a label element.

### ISSUE THREAD

**Issue by gersonkm** [uvarov-frontend/vanilla-calendar#127]
Adding 'vanilla-calendar_hidden' to the calendar element in changeToInput() doesn't hide it after picking a date when **the target input is inside a label element**.

To reproduce this issue, replace the input in https://codesandbox.io/s/hf3cgy?file=/index.html&utm_medium=sandpack with the code below:
` <label>Text <input id="calendar-input" type="text" readonly /></label>`

Now, pick a date and see if the calendar closes.

**Comment by uvarov-frontend** [comment]
According to HTML rules, a `<div>` tag cannot be placed inside a `<label>` tag.
This calendar creates a popup next to the input, the parent tag of the popup is a div, which is why the error occurs.

In any case, this is strange behavior, I did not include this in the logic.
The interesting thing is that if you replace the `label` with a `div`, then everything works correctly. I'll look into this behavior and report back.
Thanks for reporting the problem.

**Comment by gersonkm** [comment]
What about creating a popup within the body element and using absolute positioning? That's a method used by some libraries.

The strange behavior seems to be related to this line: https://github.com/uvarov-frontend/vanilla-calendar/blob/8781ebb8c6dcc57aef04637b1e9cb61e616b4a1e/package/src/scripts/methods/handlerInput.ts#L18

**Comment by gersonkm** [comment]
Additionally, wrapping the input element can cause issues with certain Bootstrap styles like floating labels.

**Comment by uvarov-frontend** [comment]
Fixed in v2.6.8
