### ISSUE TITLE
Previous date returned

### ISSUE THREAD

**Issue by onokazu** [uvarov-frontend/vanilla-calendar#130]
Hello,

I am using your script in a WordPress plugin, and some users in certain time zones reported that the previous day is returned when clicking on the calendar, and sometimes the previous day of the next month.

Since I was not able to reproduce the issue, I installed the "Change Timezone (Time Shift)" plugin on my Chrome browser, changed the timezone to "Europe/Berlin" and was able to reproduce the issue not only in the plugin but on your site as well as you can see below.

<img width="884" alt="スクリーンショット 2023-10-08 20 21 52" src="https://github.com/uvarov-frontend/vanilla-calendar/assets/88540/d422cf83-c8f4-4e76-9249-a05ff9e3d269">
<br />
<p>It would be great if you could also have a try and see what is causing such an issue, thanks!</p>

**Comment by uvarov-frontend** [comment]
Thank you for reporting the problem, I will definitely figure it out and fix it.

**Comment by uvarov-frontend** [comment]
As for the "Change Timezone (Time Shift)" plugin, it disrupts the work of the calendar because it changes the time zone in the browser while the page is loading (as far as I understand) and in general there is a suspicion that it does not work as planned.
It is more correct and reliable to change the system time in the settings of your operating system for testing.

I changed my time zone in the system settings to "Europe/Berlin" and do not see any errors, please tell me the time zone where this error occurs, thanks.

**Comment by uvarov-frontend** [comment]
If the error occurs only when using browser plugins that replace the location/time zone and time of the browser, the correct operation of the calendar cannot be guaranteed, since the browser plugin code interferes with the normal operation of the loaded js on the site.
And this is not a feature of my calendar, this is how all custom date pickers I know work. You can google any of them and see the same error.

**Comment by onokazu** [comment]
Great, thanks!
