### ISSUE TITLE
Build Process?

### ISSUE THREAD

**Issue by Tmeister** [uvarov-frontend/vanilla-calendar#4]
What is your build process to generate the .min versions?

**Comment by uvarov-frontend** [comment]
Through webpack with babel. babel config:
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react",
    "@babel/preset-typescript"
  ],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-transform-runtime"
  ]
}
```

**Comment by uvarov-frontend** [comment]
I have a repository with a universal webpack build, I did not add it here because there are a lot of files, but if you are interested:  https://github.com/uvarov-frontend/webpack-5-frontend-starter
Most likely, later I will post a lighter bander here so that you can build the plugin yourself from the source. I am considering this option: https://esbuild.github.io/

**Comment by Tmeister** [comment]
> 



> Through webpack with babel. babel config:

Great, thanks, would be great if you add it to the repo if you want to accept PR and maybe add an automatic CI/CD process.

Thanks!

**Comment by uvarov-frontend** [comment]
> > 
> 
> > Through webpack with babel. babel config:
> 
> Great, thanks, would be great if you add it to the repo if you want to accept PR and maybe add an automatic CI/CD process.
> 
> Thanks!

Okay, but first I have to finish one of the last planned features of the plugin. Time management.
![Screen-Shot-2022-07-21-21-34-27-1658428470 (2)](https://user-images.githubusercontent.com/82662379/180289311-86d31fa6-01c9-403d-919e-03553ee49835.jpeg)

**Comment by uvarov-frontend** [comment]
Added a bundler in v1.5.2. I do not plan to add automatic CI/CD.
