### ISSUE TITLE
Months not showing correctly

### ISSUE THREAD

**Issue by Ri-car-do-1989** [uvarov-frontend/vanilla-calendar#64]
I've noticed that sometimes the calendar will skip a month, repeating current month in its place.
The following screen capture is from a site I'm build using Vanilla Calendar with the 'multiple' option:
![image](https://user-images.githubusercontent.com/129438118/228942295-ccbe4228-994d-424b-a784-1884110e6ee6.png)
(The word "Março" translates to "March" in portuguese).
In the picture, month "february" is skipped, and "March" ("Março" in the image), which is the current month, gets repeated in its place.

I thought it could be a configuration issue, but then I went to the official site and saw this:

https://user-images.githubusercontent.com/129438118/228942560-278b346b-ae5c-4ae7-84e3-30e771e3c2d0.mp4

As can be ssen, the official site, without the 'multiple' option, shows "march" two times, skipping "February".
Any workaround or something I can change?

Thanks

**Comment by uvarov-frontend** [comment]
Спасибо за сообщение о проблеме, я посмотрю и исправлю это завтра.

**Comment by uvarov-frontend** [comment]
The problem is relevant since version 2.3.0. Version 2.2.8 does not have the problem with switching months, but it does not yet have `type: 'multiple'` and other new options.
I'm already working on solving this issue. Strange that I didn't notice this before.
In the future, I plan to cover everything with tests so that this does not happen. 😅

**Comment by uvarov-frontend** [comment]
One very interesting point turned out, if you set the date to the beginning of any month in the system settings of your operating system, for example `2023-03-01`, then the bug will disappear. 😄

This was due to the fact that I took the current day and added / subtracted exactly one month.
For example, today is March 31st, if I try to switch to the next month, I see that April is missing. It turns out March, then immediately May!
The fact is that in April there are only 30 days, and in March 31. On March 31, plus exactly a month, we get April 31. 😄
Since there is no such day, JS automatically switches to the next month, which is standard behavior for a `new Date` object.
Bingo! 🤓
I will fix it in v2.5.3. Just update the version and the problem will disappear.

**Comment by Ri-car-do-1989** [comment]
Thank you for your time and attention. I really liked the work you did in this calendar. Waiting for the update.

**Comment by uvarov-frontend** [comment]
I updated the version three hours ago, download 😄

**Comment by Ri-car-do-1989** [comment]
Downloaded, tested, working perfectly. Thanks.
