### ISSUE TITLE
breaking Jquery

### ISSUE THREAD

**Issue by josealissonbr** [uvarov-frontend/vanilla-calendar#85]
When trying to use vanilla calendar, commands using $(query) stop working

**Comment by josealissonbr** [comment]
![image](https://github.com/uvarov-frontend/vanilla-calendar/assets/98172458/f8442f33-8afa-42f8-98c6-b6a40ea09f56)

**Comment by uvarov-frontend** [comment]
Ok, look, you can use jquery along with vanilla js in your project, it shouldn't be a problem, but since the calendar is written in vanilla js, it doesn't understand jquery methods.

All you need is to use a couple of lines of vanilla js to initialize the calendar. The rest of the code can be jquery.

As an example, instead of `$("#calendar")`, you need to find html elements via the standard `querySelector()` method, if there are multiple elements, use `querySelectorAll()`.

**Comment by scandella** [comment]
<img width="616" alt="CleanShot 2023-06-13 at 17 02 58@2x" src="https://github.com/uvarov-frontend/vanilla-calendar/assets/1114307/37e37bac-32ac-4eac-8167-da992a7e01c3">

**Comment by uvarov-frontend** [comment]
> Hi,
> I've got the same problem and have not even initialized any calendar yet. Just adding the vanilla calendar to my project throws the error:
> Uncaught TypeError: Cannot read properties of undefined (reading 'querySelectorAll') at $ (vanilla-calendar.min.js:2:13446)
> 
> Loading the vanilla calendar into an empty project works fine.

Hi, create an example with the problem on sandcodebox, I will be happy to help fix the problem.

**Comment by scandella** [comment]
I have struggled to reproduce the problem because it seems to be a kind of race-loading script situation or something like that.
[See this code-pen](https://codepen.io/cscandella/pen/YzRyejv), look at the browser console, not the code-pen console and you'll see the exact same error I've got.
In the code pen, using "defer" on the vanilla-calendar script tag solve the problem, but in my environment, where a lot of scripts are loading, using "defer" does not change the issue.
Sorry for the fuzziness of my diagnostic.

**Comment by scandella** [comment]
Hi,
[I've made a more obvious example here.](https://codesandbox.io/s/silent-leaf-j3v7kl?file=/index.html)

If you remove the Jquey onclick function, vanilla-calendar works fine, but if you trigger a Jquery function, vanilla-calendar conflicts with Jquery.

**Comment by uvarov-frontend** [comment]
Hi, the problem is not with the plugin, but with how you combine vanilla js with jquery.
Even if you remove the plugin call and try to find the html element using the standard `querySelector` method, you will see the same error.
As an example, from your sandbox:

```
$( document ).ready(function() {
  console.log( "ready!" );
  
  console.log(document.querySelector('#calendar'))

  $( "#test" ).on( "click", function() {
    console.log('test');
  } );
});
```

Usually in this case, plugin developers will send you to stackoverflow, but it was not difficult for me to google for you. 😄
https://stackoverflow.com/questions/3931529/is-not-a-function-jquery-error
So, it is enough to wrap the code in `jQuery(function($) { ... });`.

Example:
```
jQuery(function($) {
  $(document).ready(function() {
      console.log( "ready!" );
      
      const calendar = new VanillaCalendar('#calendar');
      calendar.init();
    
      $( "#test" ).on( "click", function() {
        console.log('test');
      } );
  });
});
```

Working code in the sandbox: https://codesandbox.io/s/wild-tree-362qnc?file=/index.html

**Comment by scandella** [comment]
Thank you very much for your help. You were so right.
And kudos for your plugin: this is a great piece of software. The quality of your work is amazing: very clever choice of functionality, perfect implementation, clean design, and one of the best documentation I've seen. You deserve more than one star!

**Comment by stell** [comment]
Just stop using jQuery guys. Vanilla is much simpler and more powerful.
